### ISSUE TITLE
能否直接打包成ipk文件

### ISSUE THREAD

**Issue by JusKyle** [EkkoG/openwrt-natmap#1]
如题，
想直接导入ipk文件安装，能否直接打包ipk文件

谢谢

**Comment by EkkoG** [comment]
软件源里自己找吧，https://sourceforge.net/projects/ekko-openwrt-dist/files/packages/

**Comment by JusKyle** [comment]
> 软件源里自己找吧，https://sourceforge.net/projects/ekko-openwrt-dist/files/packages/

谢谢
